baseURL = 'https://bettgen.de/'
languageCode = 'de-de'
title = 'Niklas Bettgen – Homepage'
theme = "hugo-theme-shell"

[Params]
description = "Hi, I am a Software Engineer and an Organist. This is my private website – check it out to learn more about me and what I do."

[Params.Navbar]
use = false

[Params.Terminal]
scheme = "Tender"
userName = "nik"
pcName = "srv"
workDir = "website"
command = "git log --graph"

ps1Delay = 0
stdoutDelay = 1
commandDelay = 50

titleDelay = 3 # title speed : "title" in front matter
contentDelay = 0 # content speed : content in .md file

description = "/description.md"

[Params.Tree]
use = true
folderName = "my-skills"
files = [
	["c/c++", "#"],
	["TypeScript", "#"],
	["Python", "#"],
	["Docker", "#"],
	["Shell Scripting", "#"],
	["IoT", "#"],
	["Industrial Automation", "#"],
	["Brainf*ck", "https://en.wikipedia.org/wiki/Brainfuck"],
]
